baseURL = "https://antoanyosifov.com"
languageCode = "en-us"
title = "Antoan Yosifov"
theme = "hugo-noir"

relativeURLs = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
name = "Antoan Yosifov"
location = "Aschach an der Donau, Austria"
description = "Junior engineer with strong fundamentals and real project experience in Java/Spring/Angular."
profile_image = "/images/profile.png"


# contact/social
email = "antoan.yosifov23@gmail.com"

linkedin = "https://www.linkedin.com/in/antoan-yosifov-b1b52026b"
linkedin_username = "Antoan Yosifov"
github             = "https://github.com/AntoanYosifov"
github_username    = "AntoanYosifov"

[[params.projects]]
title = "TravelHub"
description =  "TravelHub is a real-time travel app built with Angular and Firebase where users discover destinations, like each once, and save a personal “want-to-visit” list. Secure auth, profile management, and ownership rules power a smooth, reactive UI."
tech = "Angular (Signals), TypeScript, RxJS, HTML, CSS, Firebase — Firestore, Authentication, GitHub Pages"
image = "/images/projects/TravelHub.png"
link = "https://github.com/AntoanYosifov/travel-hub"
liveLink = "https://antoanyosifov.github.io/travel-hub/"


[[params.projects]]
title = "BrainDissecting"
description = "A web platform that aggregates, moderates, and curates open‑access scientific articles via the DOAJ API, with built‑in role‑based access control for admins, moderators, and users."
tech = "Java21, SpringBoot3.3.2, Spring Security, Spring Data JPA, Hibernate/JPA, Thymeleaf, Bootstrap5, DOAJ API, MySQL, Docker, Railway (Cloud)"
image = "/images/projects/BrainDissecting.png"
link = "https://github.com/AntoanYosifov/BrainDissecting-SSR-version"
liveLink = "https://braindissecting-ssr-version-production.up.railway.app/"


[[params.education]]
title = "Software University (SoftUni) Sofia (Bulgaria)"
image = "/images/education/uni-logo.png"
mainLink = "https://softuni.org/"
altLink = "https://softuni.bg/"

[[params.education]]
title = "Angular June 2025"
image = "/images/education/angular.jpeg"
certificateLink = "https://softuni.bg/certificates/details/250024/b150a58a"

[[params.education]]
title = "Git May 2025"
image = "/images/education/git.jpeg"
certificateLink = "https://softuni.bg/certificates/details/247012/89c53d18"

[[params.education]]
title = "JS Front-End February 2025"
image = "/images/education/js-front-end.jpeg"
certificateLink = "https://softuni.bg/certificates/details/242308/50b3144d"

[[params.education]]
title = "HTML & CSS January 2025"
image = "/images/education/html&css.jpeg"
certificateLink = "https://softuni.bg/certificates/details/238004/e3c7f8e7"

[[params.education]]
title = "Spring Fundamentals May 2024"
image = "/images/education/spring-fundamentals.jpeg"
certificateLink = "https://softuni.bg/certificates/details/242308/50b3144d"

[[params.education]]
title = "Spring Data February 2024"
image = "/images/education/spring-data.jpeg"
certificateLink = "https://softuni.bg/certificates/details/209296/601d2151"

[[params.education]]
title = "MySQL January 2024"
image = "/images/education/my-sql.jpeg"
certificateLink = "https://softuni.bg/certificates/details/202712/c0eb046a"

[[params.education]]
title = "Java OOP October 2023"
image = "/images/education/java-oop.jpeg"
certificateLink = "https://softuni.bg/certificates/details/200860/2cb65e96"

[[params.education]]
title = "Java Advanced September 2023"
image = "/images/education/java-advanced.jpeg"
certificateLink = "https://softuni.bg/certificates/details/188586/ac6687dc"

[[params.education]]
title = "Java Fudnamentals May 2023"
image = "/images/education/java-fundamentals.jpeg"
certificateLink = "https://softuni.bg/certificates/details/179830/b9a08faf"


[menu]
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "Education"
url = "/education/"
weight = 4
